name: microsoft_teams_clone
description: A new Flutter project.
publish_to: 'none'
version: 1.6.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

  # Firebase storage Dependencies
  cloud_firestore:
  firebase_storage:
  
  #google sign in 
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  google_sign_in: ^5.0.0

  #state management for google:
  provider:
    
  # Jitsi meet Dependencies
  jitsi_meet:

  # Stream Chat Dependencies
  flutter_app_badger: ^1.2.0
  flutter:
    sdk: flutter
  stream_chat_flutter:
    git:
      url: https://github.com/GetStream/stream-chat-flutter.git
      ref: develop
      path: packages/stream_chat_flutter
  stream_chat_persistence:
    git:
      url: https://github.com/GetStream/stream-chat-flutter.git
      ref: develop
      path: packages/stream_chat_persistence
  flutter_local_notifications: ^5.0.0+4
  flutter_svg: ^0.22.0
  flutter_secure_storage: ^4.2.0
  yaml: ^3.1.0
  streaming_shared_preferences: ^2.0.0
  lottie: ^1.0.1
  collection: ^1.15.0-nullsafety.4

  # Common
  uuid: ^3.0.4
  intl:
  pin_code_fields:
  flutter_custom_clippers:
  font_awesome_flutter:

dependency_overrides:
  stream_chat:
    git:
      url: https://github.com/GetStream/stream-chat-flutter.git
      ref: develop
      path: packages/stream_chat
  stream_chat_flutter_core:
    git:
      url: https://github.com/GetStream/stream-chat-flutter.git
      ref: develop
      path: packages/stream_chat_flutter_core

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  test: any
flutter:
  assets:
    - assets/icons/
    - assets/images/
    - pubspec.lock
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/android_icon.png"
  image_path_ios: "assets/ios_icon.png"
